foxglove_bridge:
  ros__parameters:
    use_compression: true
    topic_whitelist:
      - "^/rosout$"
      - "^/parameter_events$"
      - "^/tf$"
      - "^/tf_static$"
      - "^/odom$"
      - "^/imu$"
      - "^/imu/data$"
      - "^/battery_state$"
      - "^/cmd_vel$"
      - "^/xgo/applied_vel$"
      - "^/xgo/yaw_deg$"
      - "^/scan$"
      - "^/scan_filtered$"
      - "^/map$"
      - "^/map_metadata$"
      - "^/dynamic_scan_filter/cluster_markers$"
      - "^/dynamic_scan_filter/removed_static_objects$"
      - "^/camera/camera_info$"
      - "^/camera/image_raw/compressed$"
