<?xml version="1.0"?>
<package format="3">
  <name>xgo_driver_bridge</name>
  <version>0.0.1</version>
  <description>ROS 2 bridge for the XGO Mini2 Python SDK.</description>
  <maintainer email="ros@todo.todo">ros</maintainer>
  <license>MIT</license>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>builtin_interfaces</depend>
  <depend>tf2_ros</depend>
  <exec_depend>tf2_ros_py</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>camera_ros</exec_depend>
  <exec_depend>cartographer_ros</exec_depend>
  <exec_depend>dynamic_scan_filter</exec_depend>
  <exec_depend>foxglove_bridge</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ldlidar_stl_ros2</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>rtabmap_slam</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
